USE [master]
GO

/****** Object:  Database [BancoNacion]    Script Date: 8/9/2023 10:40:42 ******/
CREATE DATABASE [BancoNacion]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BancoNacion', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BancoNacion.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BancoNacion_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BancoNacion_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BancoNacion].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BancoNacion] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BancoNacion] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BancoNacion] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BancoNacion] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BancoNacion] SET ARITHABORT OFF 
GO

ALTER DATABASE [BancoNacion] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BancoNacion] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BancoNacion] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BancoNacion] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BancoNacion] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BancoNacion] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BancoNacion] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BancoNacion] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BancoNacion] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BancoNacion] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BancoNacion] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BancoNacion] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BancoNacion] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BancoNacion] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BancoNacion] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BancoNacion] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BancoNacion] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BancoNacion] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BancoNacion] SET  MULTI_USER 
GO

ALTER DATABASE [BancoNacion] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BancoNacion] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BancoNacion] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BancoNacion] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BancoNacion] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BancoNacion] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BancoNacion] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BancoNacion] SET  READ_WRITE 
GO

